# Generated by Django 6.0.2 on 2026-05-10 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='company',
            fields=[
                ('company_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(verbose_name=50)),
                ('location', models.CharField(verbose_name=50)),
                ('about', models.TextField()),
                ('type', models.CharField(choices=[('It', 'It'), ('Non IT', 'Non It'), ('Mobile Phone', 'Mobile Phone')], max_length=100)),
                ('added_date', models.DateTimeField(auto_now=True)),
                ('active', models.BooleanField(default=True)),
            ],
        ),
    ]
