# Generated by Django 6.0.2 on 2026-05-11 08:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_company_location_alter_company_name_employee'),
    ]

    operations = [
        migrations.RenameField(
            model_name='employee',
            old_name='Company',
            new_name='company',
        ),
    ]
